echo "Проверка синтезатора речи" | RHVoice-test -p "anna"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "anna"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "arina"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "artemiy"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "elena"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "evgeniy-rus"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "irina"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "mikhail"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "pavel"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "tatiana"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "victoria"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "vitaliy"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "yuriy"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "pavel"
echo "Танюшка привет! Как твои дела?" | RHVoice-test -p "vitaliy"

